const [Gousts,setGousts]=useState([
    { id: 1,
      name:"Elias Walker", 
      age: "born in 1976", 
      job: "The retired Army Captain and leader of the Ghosts",
      rank: "Lieutenant (2005-2015), Captain (2015-2027)",
      img: "https://vignette.wikia.nocookie.net/callofduty/images/7/76/Elias_walker.png/revision/latest?cb=20140527094731&path-prefix=de"
    },
    { id: 2,
      name:"Logan Walker", 
      age: "26", 
      job: "Soldier",
      rank: "Sergeant",
      img: "https://tse1.mm.bing.net/th/id/OIP.8jbuZ39f0PWL5lJhu0bLUgHaHa?rs=1&pid=ImgDetMain&o=7&rm=3"
    },
    { id: 3,
      name:'David "Hesh" Walker', 
      age: "28", 
      job: "Soldier",
      rank: "Lieutenant",
      img: "https://i.pinimg.com/736x/a7/30/55/a73055d0fafc7643c7b6a001c6020ddb.jpg"
    },
    { id: 4,
      name:"Keegan P. Russ", 
      age: "38", 
      job: "Scout sniper",
      rank: "Sergeant",
      img: "https://i.pinimg.com/736x/af/40/bc/af40bc510727d7cc55f8744815a66ce9.jpg"
    }, 
    { id: 5,
      name:"Cdr. Thomas A. Merrick", 
      age: "39 yers ol in 2027", 
      job: "Soldier",
      rank: "Petty Officer 2nd Class Captain",
      img: "https://tse1.mm.bing.net/th/id/OIP.sC_dQkyY8t4k0RUUaX5-zQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3"
    },
    { id: 6,
      name:"Gabriel T. Rorke", 
      age: "53", 
      job: '(was Soldier) now "The Ghost Killer"',
      rank: "Commander (Ghosts), Captain (formerly; Ghosts)",
      img: "https://th.bing.com/th/id/OIP.Jc-AiQ03m8907h1mwbrmRgHaHa?w=200&h=200&c=10&o=6&pid=genserp&rm=2"
    }])
  const [MW2, setMW2]=useState([
    { id: 1,
      name:"Captain John Price", 
      age: "37", 
      job: "Commanding officer of Task Force 141",
      rank: "Captain, Lieutenant (2011)",
      img: "https://th.bing.com/th/id/OIP.75TCPeGYBxgzSJGZX3-XDQHaIq?w=200&h=200&c=10&o=6&pid=genserp&rm=2"
    },
    { id: 2,
      name:'Simon "Ghost" Riley', 
      age: "38", 
      job: "British special forces operator",
      rank: "Lieutenant",
      img: "https://th.bing.com/th/id/R.e5f2b3ad049e6454c850346c20a2e3a0?rik=eJUq7RNROE9l5Q&pid=ImgRaw&r=0"
    },
    { id: 3,
      name:"Gaz", 
      age: "25-27", 
      job: "Soldier",
      rank: "Sergeant",
      img: "https://static1.thegamerimages.com/wordpress/wp-content/uploads/2022/10/Gaz-MW2.jpg"
    },
    { id: 4,
      name:"Soap MacTavish", 
      age: "26", 
      job: "Sniper and demolitions expert",
      rank: "Sergeant",
      img: "https://th.bing.com/th/id/OIP.5lb90-fHTcbGYcIF32Hz1wHaHa?w=200&h=200&c=10&o=6&pid=genserp&rm=2"
    },
    { id: 5,
      name:"Colonel Alejandro Vargas", 
      age: "~35", 
      job: "Colonel in the Mexican Special Forces",
      rank: "Colonel",
      img: "https://th.bing.com/th/id/OIP.AUmxVRx3repkUbpSqxReQwAAAA?w=200&h=312&c=10&o=6&pid=genserp&rm=2"
    },
  ])